"""wind and solar power plant config models

Revision ID: 2cf9f584f068
Revises: eabab3cc72ea
Create Date: 2025-02-04 03:09:40.659595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2cf9f584f068'
down_revision: Union[str, None] = 'eabab3cc72ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'solar_power_plant_configs',
        sa.Column('power_plant_id', sa.UUID(), nullable=False),
        sa.Column('total_capacity', sa.Float(precision=32), nullable=True),
        sa.Column('module_count', sa.Integer(), nullable=False),
        sa.Column('module_power', sa.Integer(), nullable=False),
        sa.Column('inverter_model', sa.String(length=30), nullable=True),
        sa.Column('inverter_count', sa.Integer(), nullable=False),
        sa.Column('inverter_power', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['power_plant_id'], ['power_plants.id'], ),
        sa.PrimaryKeyConstraint('power_plant_id')
    )
    op.create_table(
        'wind_power_plant_configs',
        sa.Column('power_plant_id', sa.UUID(), nullable=False),
        sa.Column('production_year', sa.Integer(), nullable=True),
        sa.Column('tower_height', sa.Float(precision=8), nullable=True),
        sa.Column('rotor_diameter', sa.Float(precision=8), nullable=True),
        sa.Column('start_speed', sa.Float(precision=8), nullable=True),
        sa.Column('stop_speed', sa.Float(precision=8), nullable=True),
        sa.Column('max_speed_limit', sa.Float(precision=8), nullable=True),
        sa.ForeignKeyConstraint(['power_plant_id'], ['power_plants.id'], ),
        sa.PrimaryKeyConstraint('power_plant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wind_power_plant_configs')
    op.drop_table('solar_power_plant_configs')
    # ### end Alembic commands ###
