"""power plant model

Revision ID: eabab3cc72ea
Revises: 
Create Date: 2025-02-04 02:06:59.593227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'eabab3cc72ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'power_plants',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=True),
        sa.Column('model', sa.String(length=30), nullable=True),
        sa.Column('longitude', sa.Float(precision=8), nullable=False),
        sa.Column('latitude', sa.Float(precision=8), nullable=False),
        sa.Column('category', sa.Enum('SOLAR', 'EOLIAN', name='power_plant_category'), nullable=False),
        sa.Column('power', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('power_plants')
    # ### end Alembic commands ###
